import logger from "../lib/logger";
import prisma from "../prisma";

const amenities = [
  "Gymnasium",
  "Swimming Pool",
  "Badminton Court(s)",
  "Tennis Court(s)",
  "Squash Court",
  "Kids' Play Areas",
  "Jogging / Cycle Track",
  "Power Backup",
  "Central AC",
  "Central Wi-Fi",
  "Attached Market",
  "Restaurant",
  "Home Automation",
  "24 x 7 Security",
  "Clubhouse",
  "Balcony",
  "High Speed Elevators",
  "Pre-School",
  "Medical Facility",
  "Day Care Center",
  "Pet Area",
  "Indoor Games",
  "Conference Room",
  "Large Green Area",
  "Concierge Desk",
  "Helipad",
  "Golf Course",
  "Multiplex",
  "Visitor's Parking",
  "Serviced Apartments",
  "Service Elevators",
  "High Street Retail",
  "Hypermarket",
  "ATM's",
  "Food Court",
  "Servant Quarter",
  "Study Room",
  "Private Pool",
  "Private Gym",
  "Private Jacuzzi",
  "View of Water",
  "View of Landmark",
  "Built in Wardrobes",
  "Walk-in Closet",
  "Lobby in Building",
  "Barbeque Area",
  "Double Glazed Windows",
  "Centrally Air-Conditioned",
  "Central Heating",
  "Electricity Backup",
  "Waste Disposal",
  "First Aid Medical Center",
  "Tiles",
  "Broadband Internet",
  "Satellite/Cable TV",
  "Intercom",
  "Jacuzzi",
  "Kids Play Area",
  "Reception/Waiting Room",
  "Maintenance Staff",
  "Sauna",
  "Security Staff",
  "CCTV Security",
  "Laundry Facility",
  "Cleaning Services",
  "Facilities for Disabled",
  "24 Hours Concierge",
  "Balcony or Terrace",
];

prisma.amenity
  .createMany({
    data: amenities.map((amenity) => ({ name: amenity })),
  })
  .then(() => {
    logger.info("Added amenities to database.");
  })
  .catch((error) => {
    logger.error(error);
  });
